"use client";

import { Check, Copy, FileCode2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { toolkitApi, ToolkitApiError } from "@/lib/toolkitApi";

type PermissionLevel = "everyone" | "vip" | "mod" | "streamer";

interface ClipPlayPermissions {
  play: PermissionLevel;
  playStop: PermissionLevel;
}

interface ClipPlaySettings {
  chatNoUrlMessage: string;
  chatUnsupportedMessage: string;
  commandName: string;
  loadingDelayBufferMs: number;
  maxDurationSec: number;
  obsBrowserSource: string;
  obsScene: string;
  overlayUrl: string;
  permissions: ClipPlayPermissions;
  stopCommandName: string;
  volumeNormalize: boolean;
  volumeTargetDb: number;
}

const DEFAULT_SETTINGS: ClipPlaySettings = {
  chatNoUrlMessage: "Usage: !play <url>",
  chatUnsupportedMessage:
    "Link format not supported. Try a Twitch clip, YouTube, TikTok, Instagram Reel, or Facebook video.",
  commandName: "!play",
  loadingDelayBufferMs: 1000,
  maxDurationSec: 300,
  obsBrowserSource: "VRF-CPL",
  obsScene: "Screenshare",
  overlayUrl: "https://deutschmark.online/clip-play/",
  permissions: {
    play: "everyone",
    playStop: "mod",
  },
  stopCommandName: "!playstop",
  volumeNormalize: true,
  volumeTargetDb: -14,
};

const PERMISSION_LEVELS: readonly PermissionLevel[] = ["everyone", "vip", "mod", "streamer"];

const COMMANDS: Array<{ key: keyof ClipPlayPermissions; label: string; note: string }> = [
  { key: "play", label: "!play <url>", note: "Play a clip or video in the overlay" },
  { key: "playStop", label: "!playstop", note: "Immediately clear the overlay" },
];

const SUPPORTED_PLATFORMS = [
  { examples: ["clips.twitch.tv/SlugName"], label: "Twitch Clips" },
  {
    examples: ["youtube.com/watch?v=…", "youtu.be/…", "youtube.com/shorts/…"],
    label: "YouTube & Shorts",
  },
  { examples: ["tiktok.com/@user/video/…"], label: "TikTok" },
  { examples: ["instagram.com/reel/…", "instagram.com/p/…"], label: "Instagram Reels" },
  { examples: ["facebook.com/…/videos/…", "facebook.com/watch?v=…"], label: "Facebook Videos" },
];

/* ─── Script Generator ─── */

function generatePlayScript(s: ClipPlaySettings): string {
  return `// ================================================================
// Clip Play — generated by toolkit.deutschmark.online
// Edit config: https://toolkit.deutschmark.online/tools/clip-play
// ================================================================
// Trigger:  Chat command → ${s.commandName}  (with "Add To Arguments" checked)
// Input:    rawInput = the URL typed after the command
// ================================================================
using System;
using System.Text.RegularExpressions;

public class CPHInline
{
    // ── OBS Configuration ──────────────────────────────────────────
    private const string OBS_SCENE  = ${JSON.stringify(s.obsScene)};
    private const string OBS_SOURCE = ${JSON.stringify(s.obsBrowserSource)};

    // ── Playback Configuration ─────────────────────────────────────
    private const int  MAX_DURATION_SEC = ${s.maxDurationSec};
    private const int  DELAY_BUFFER_MS  = ${s.loadingDelayBufferMs};
    private const bool NORMALIZE        = ${s.volumeNormalize ? "true" : "false"};
    private const int  TARGET_DB        = ${s.volumeTargetDb};

    // ── Overlay URL ────────────────────────────────────────────────
    private const string OVERLAY_URL = ${JSON.stringify(s.overlayUrl)};

    // ── Chat Messages ──────────────────────────────────────────────
    private const string NO_URL_MSG      = ${JSON.stringify(s.chatNoUrlMessage)};
    private const string UNSUPPORTED_MSG = ${JSON.stringify(s.chatUnsupportedMessage)};

    public bool Execute()
    {
        string rawUrl = args.ContainsKey("rawInput")
            ? args["rawInput"].ToString().Trim()
            : string.Empty;

        if (string.IsNullOrEmpty(rawUrl))
        {
            CPH.SendMessage(NO_URL_MSG);
            return false;
        }

        string embedUrl, platform;
        if (!TryConvertUrl(rawUrl, out embedUrl, out platform))
        {
            CPH.SendMessage(UNSUPPORTED_MSG);
            return false;
        }

        string url = OVERLAY_URL
            + "?url="       + Uri.EscapeDataString(embedUrl)
            + "&platform="  + Uri.EscapeDataString(platform)
            + "&normalize=" + (NORMALIZE ? "1" : "0")
            + "&target_db=" + TARGET_DB;

        CPH.ObsSetBrowserSource(OBS_SCENE, OBS_SOURCE, url);
        CPH.Wait(MAX_DURATION_SEC * 1000 + DELAY_BUFFER_MS);
        CPH.ObsSetBrowserSource(OBS_SCENE, OBS_SOURCE, "about:blank");
        return true;
    }

    private static bool TryConvertUrl(string url,
        out string embedUrl, out string platform)
    {
        // Twitch clip
        var twitch = Regex.Match(url,
            @"clips\\.twitch\\.tv/([A-Za-z0-9_-]+)");
        if (twitch.Success)
        {
            embedUrl = "https://clips.twitch.tv/embed?clip=" + twitch.Groups[1].Value;
            platform = "twitch";
            return true;
        }

        // YouTube watch / short URL
        var yt = Regex.Match(url,
            @"(?:youtube\\.com/watch\\?v=|youtu\\.be/)([A-Za-z0-9_-]{11})");
        if (yt.Success)
        {
            embedUrl = "https://www.youtube.com/embed/" + yt.Groups[1].Value
                     + "?autoplay=1&rel=0";
            platform = "youtube";
            return true;
        }

        // YouTube Shorts
        var ytShorts = Regex.Match(url,
            @"youtube\\.com/shorts/([A-Za-z0-9_-]{11})");
        if (ytShorts.Success)
        {
            embedUrl = "https://www.youtube.com/embed/" + ytShorts.Groups[1].Value
                     + "?autoplay=1&rel=0";
            platform = "youtube";
            return true;
        }

        // TikTok
        var tt = Regex.Match(url,
            @"tiktok\\.com/@[^/]+/video/(\\d+)");
        if (tt.Success)
        {
            embedUrl = "https://www.tiktok.com/embed/v2/" + tt.Groups[1].Value;
            platform = "tiktok";
            return true;
        }

        // Instagram Reel / post
        var ig = Regex.Match(url,
            @"instagram\\.com/(?:reel|p)/([A-Za-z0-9_-]+)");
        if (ig.Success)
        {
            embedUrl = "https://www.instagram.com/p/" + ig.Groups[1].Value + "/embed/";
            platform = "instagram";
            return true;
        }

        // Facebook video / watch / reel
        if (url.Contains("facebook.com") &&
            (url.Contains("/video") || url.Contains("/watch") || url.Contains("/reel")))
        {
            embedUrl = "https://www.facebook.com/plugins/video.php?href="
                     + Uri.EscapeDataString(url)
                     + "&show_text=false&autoplay=true&mute=false";
            platform = "facebook";
            return true;
        }

        embedUrl = string.Empty;
        platform = string.Empty;
        return false;
    }
}`;
}

function generateStopScript(s: ClipPlaySettings): string {
  return `// ================================================================
// Clip Play — Stop command
// Trigger: Chat command → ${s.stopCommandName}
// ================================================================
public class CPHInline
{
    private const string OBS_SCENE  = ${JSON.stringify(s.obsScene)};
    private const string OBS_SOURCE = ${JSON.stringify(s.obsBrowserSource)};

    public bool Execute()
    {
        CPH.ObsSetBrowserSource(OBS_SCENE, OBS_SOURCE, "about:blank");
        return true;
    }
}`;
}

/* ─── Shared UI helpers ─── */

function Toggle({ checked, onChange, disabled }: {
  checked: boolean;
  disabled?: boolean;
  onChange: (v: boolean) => void;
}) {
  return (
    <button
      aria-checked={checked}
      className={[
        "relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer items-center rounded-full transition-colors",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--toolkit-accent)]",
        disabled ? "cursor-not-allowed opacity-40" : "",
        checked ? "bg-[var(--toolkit-accent)]" : "bg-[var(--toolkit-border-strong)]",
      ].join(" ")}
      disabled={disabled}
      onClick={() => onChange(!checked)}
      role="switch"
      type="button"
    >
      <span
        className={[
          "inline-block h-4 w-4 rounded-full bg-white shadow transition-transform",
          checked ? "translate-x-6" : "translate-x-1",
        ].join(" ")}
      />
    </button>
  );
}

function FormRow({ label, note, children }: {
  children: React.ReactNode;
  label: string;
  note?: string;
}) {
  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between sm:gap-6">
      <div className="min-w-0 sm:max-w-[220px]">
        <span className="text-sm text-[var(--toolkit-text)]">{label}</span>
        {note && <p className="mt-0.5 text-xs leading-5 text-[var(--toolkit-text-dim)]">{note}</p>}
      </div>
      <div className="w-full sm:max-w-xs">{children}</div>
    </div>
  );
}

/* ─── Script Panel ─── */

type ScriptTab = "play" | "stop";

function ScriptPanel({ settings }: { settings: ClipPlaySettings }) {
  const [tab, setTab] = useState<ScriptTab>("play");
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const script = tab === "play" ? generatePlayScript(settings) : generateStopScript(settings);

  function copy() {
    navigator.clipboard.writeText(script).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="toolkit-eyebrow">Streamer.bot scripts</p>
          <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
            Generated C# scripts
          </h2>
          <p className="mt-1 text-sm leading-6 text-[var(--toolkit-text-muted)]">
            Two separate Streamer.bot actions — one for play, one for stop. Re-copy after saving
            config changes.
          </p>
        </div>
        <div className="flex shrink-0 gap-2">
          <button
            className="toolkit-button toolkit-button-ghost text-xs"
            onClick={() => setExpanded(v => !v)}
            type="button"
          >
            <FileCode2 className="h-4 w-4" />
            {expanded ? "Collapse" : "Preview"}
          </button>
          <button
            className="toolkit-button toolkit-button-primary shrink-0"
            onClick={copy}
            type="button"
          >
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? "Copied!" : "Copy script"}
          </button>
        </div>
      </div>

      {/* Tab switcher */}
      <div className="mt-4 flex gap-1 rounded-[var(--toolkit-radius-md)] border border-[var(--toolkit-border-strong)] bg-[var(--toolkit-bg-subtle)] p-1">
        {(["play", "stop"] as ScriptTab[]).map(t => (
          <button
            key={t}
            className={[
              "flex-1 rounded-[10px] px-3 py-1.5 text-xs font-medium transition-colors",
              tab === t
                ? "bg-[rgba(var(--toolkit-accent-rgb),0.14)] text-[var(--toolkit-text-strong)] border border-[rgba(var(--toolkit-accent-rgb),0.2)]"
                : "text-[var(--toolkit-text-muted)] hover:text-[var(--toolkit-text-strong)]",
            ].join(" ")}
            onClick={() => setTab(t)}
            type="button"
          >
            {t === "play"
              ? `${settings.commandName} — play`
              : `${settings.stopCommandName} — stop`}
          </button>
        ))}
      </div>

      {expanded && (
        <pre className="mt-4 overflow-x-auto rounded-[var(--toolkit-radius-md)] border border-[var(--toolkit-border-strong)] bg-[var(--toolkit-bg-subtle)] p-4 text-xs leading-5 text-[var(--toolkit-text-muted)]">
          {script}
        </pre>
      )}

      <div className="mt-4 rounded-[var(--toolkit-radius-md)] border border-[var(--toolkit-border)] bg-[var(--toolkit-bg-subtle)] px-4 py-3">
        <p className="text-xs leading-5 text-[var(--toolkit-text-dim)]">
          <strong className="text-[var(--toolkit-text-muted)]">Streamer.bot setup:</strong> Create
          two actions — one triggered by{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1 font-mono">
            {settings.commandName}
          </code>{" "}
          (paste play script, enable "Add To Arguments" on the trigger so{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1 font-mono">rawInput</code> is
          populated), and one triggered by{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1 font-mono">
            {settings.stopCommandName}
          </code>{" "}
          (paste stop script). OBS WebSocket must be connected.
        </p>
      </div>
    </section>
  );
}

/* ─── Main Page ─── */

export default function ClipPlayPage() {
  const [settings, setSettings] = useState<ClipPlaySettings>(DEFAULT_SETTINGS);
  const [savedSettings, setSavedSettings] = useState<ClipPlaySettings>(DEFAULT_SETTINGS);
  const [isLoading, setIsLoading] = useState(true);
  const [settingsLoaded, setSettingsLoaded] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [saveMessage, setSaveMessage] = useState<{
    text: string;
    tone: "success" | "error";
  } | null>(null);
  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const isDirty = settingsLoaded && JSON.stringify(settings) !== JSON.stringify(savedSettings);

  useEffect(() => {
    toolkitApi
      .get<{ settings: ClipPlaySettings }>("/clip-play-settings")
      .then(data => {
        const merged: ClipPlaySettings = {
          ...DEFAULT_SETTINGS,
          ...data.settings,
          permissions: { ...DEFAULT_SETTINGS.permissions, ...(data.settings?.permissions ?? {}) },
        };
        setSettings(merged);
        setSavedSettings(merged);
        setSettingsLoaded(true);
      })
      .catch(err => {
        const msg =
          err instanceof ToolkitApiError && err.status === 401
            ? "Sign in to load your Clip Play settings."
            : "Couldn't load saved settings. Retry before making changes.";
        setLoadError(msg);
      })
      .finally(() => setIsLoading(false));
  }, []);

  useEffect(() => {
    if (!isDirty) return;
    const handler = (e: BeforeUnloadEvent) => e.preventDefault();
    window.addEventListener("beforeunload", handler);
    return () => window.removeEventListener("beforeunload", handler);
  }, [isDirty]);

  const save = useCallback(async () => {
    if (isSaving || !settingsLoaded) return;
    setIsSaving(true);
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current);

    try {
      const data = await toolkitApi.put<{ settings: ClipPlaySettings }>(
        "/clip-play-settings",
        settings,
      );
      const merged: ClipPlaySettings = {
        ...DEFAULT_SETTINGS,
        ...data.settings,
        permissions: { ...DEFAULT_SETTINGS.permissions, ...(data.settings?.permissions ?? {}) },
      };
      setSettings(merged);
      setSavedSettings(merged);
      setSaveMessage({ text: "Saved.", tone: "success" });
    } catch (err) {
      const msg = err instanceof ToolkitApiError ? err.message || "Save failed." : "Save failed.";
      setSaveMessage({ text: msg, tone: "error" });
    } finally {
      setIsSaving(false);
      saveTimerRef.current = setTimeout(() => setSaveMessage(null), 4000);
    }
  }, [isSaving, settings, settingsLoaded]);

  function setPermission(key: keyof ClipPlayPermissions, level: PermissionLevel) {
    setSettings(prev => ({
      ...prev,
      permissions: { ...prev.permissions, [key]: level },
    }));
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <section className="toolkit-surface px-4 py-5 text-[var(--toolkit-text-strong)] sm:px-6 sm:py-7">
        <p className="toolkit-eyebrow">Clip play workflow</p>
        <h1 className="mt-4 text-2xl font-semibold tracking-[-0.06em] sm:text-3xl">
          Clip Play
        </h1>
        <p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--toolkit-text-muted)]">
          Let chat drop a Twitch clip, YouTube video, TikTok, Instagram Reel, or Facebook video
          into an OBS browser source overlay with a single{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1.5 py-0.5 text-xs font-mono">
            {settings.commandName}
          </code>{" "}
          command. Volume normalization keeps all sources at a consistent level.
        </p>
      </section>

      {loadError && (
        <div className="toolkit-surface border-[var(--toolkit-danger)]/30 px-4 py-4 sm:px-6">
          <p className="text-sm text-[var(--toolkit-danger)]">{loadError}</p>
        </div>
      )}

      {/* OBS & Commands */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">OBS & commands</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Scene, source, and trigger names
        </h2>
        <div className="mt-5 space-y-5">
          <FormRow
            label="Play command"
            note="Chat command for playing a link (must start with !)."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              maxLength={32}
              onChange={e => setSettings(s => ({ ...s, commandName: e.target.value }))}
              placeholder="!play"
              type="text"
              value={settings.commandName}
            />
          </FormRow>
          <FormRow
            label="Stop command"
            note="Clears the overlay immediately (must start with !)."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              maxLength={32}
              onChange={e => setSettings(s => ({ ...s, stopCommandName: e.target.value }))}
              placeholder="!playstop"
              type="text"
              value={settings.stopCommandName}
            />
          </FormRow>
          <div className="border-t border-[var(--toolkit-border)] pt-5" />
          <FormRow
            label="OBS scene name"
            note="The scene that contains the clip play browser source."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              maxLength={100}
              onChange={e => setSettings(s => ({ ...s, obsScene: e.target.value }))}
              placeholder="Screenshare"
              type="text"
              value={settings.obsScene}
            />
          </FormRow>
          <FormRow
            label="Browser source name"
            note="Name of the OBS browser source for clip playback."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              maxLength={100}
              onChange={e => setSettings(s => ({ ...s, obsBrowserSource: e.target.value }))}
              placeholder="VRF-CPL"
              type="text"
              value={settings.obsBrowserSource}
            />
          </FormRow>
        </div>
      </section>

      {/* Playback Settings */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Playback</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Duration and timing
        </h2>
        <div className="mt-5 space-y-5">
          <FormRow
            label="Max duration (sec)"
            note="Overlay closes after this many seconds. Used for all platforms since video length isn't always known in advance."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              max={600}
              min={5}
              onChange={e => {
                const v = parseInt(e.target.value, 10);
                if (!Number.isNaN(v)) setSettings(s => ({ ...s, maxDurationSec: v }));
              }}
              type="number"
              value={settings.maxDurationSec}
            />
          </FormRow>
          <FormRow
            label="Post-play delay buffer (ms)"
            note="Extra milliseconds added after max duration before the overlay is cleared."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              max={10000}
              min={0}
              step={100}
              onChange={e => {
                const v = parseInt(e.target.value, 10);
                if (!Number.isNaN(v)) setSettings(s => ({ ...s, loadingDelayBufferMs: v }));
              }}
              type="number"
              value={settings.loadingDelayBufferMs}
            />
          </FormRow>
        </div>
      </section>

      {/* Volume Normalization */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Audio</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Volume normalization
        </h2>
        <p className="mt-1 text-sm leading-6 text-[var(--toolkit-text-muted)]">
          The overlay page uses the Web Audio API to normalize playback volume so Twitch clips,
          YouTube videos, and TikToks all land near the same output level without OBS post-processing.
        </p>
        <div className="mt-5 space-y-5">
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-[var(--toolkit-text)]">Enable normalization</p>
              <p className="mt-0.5 text-xs text-[var(--toolkit-text-dim)]">
                Applies a gain correction to each clip based on its measured loudness.
              </p>
            </div>
            <Toggle
              checked={settings.volumeNormalize}
              disabled={isLoading}
              onChange={v => setSettings(s => ({ ...s, volumeNormalize: v }))}
            />
          </div>
          <FormRow
            label="Target level (dBFS)"
            note="The loudness target applied during normalization. –14 dBFS is a good broadcast default; lower values are quieter."
          >
            <input
              className="toolkit-input"
              disabled={isLoading || !settings.volumeNormalize}
              max={0}
              min={-40}
              onChange={e => {
                const v = parseInt(e.target.value, 10);
                if (!Number.isNaN(v)) setSettings(s => ({ ...s, volumeTargetDb: v }));
              }}
              type="number"
              value={settings.volumeTargetDb}
            />
          </FormRow>
        </div>
      </section>

      {/* Overlay URL */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Overlay</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Overlay URL
        </h2>
        <p className="mt-1 text-sm leading-6 text-[var(--toolkit-text-muted)]">
          The HTML page loaded by the OBS browser source. The script appends{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1 font-mono text-xs">
            ?url=&platform=&normalize=&target_db=
          </code>{" "}
          as query params.
        </p>
        <div className="mt-4">
          <input
            className="toolkit-input"
            disabled={isLoading}
            maxLength={500}
            onChange={e => setSettings(s => ({ ...s, overlayUrl: e.target.value }))}
            placeholder="https://deutschmark.online/clip-play/"
            type="text"
            value={settings.overlayUrl}
          />
        </div>
      </section>

      {/* Supported Platforms */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Supported platforms</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          URL formats the script recognises
        </h2>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {SUPPORTED_PLATFORMS.map(p => (
            <div
              key={p.label}
              className="rounded-[var(--toolkit-radius-md)] border border-[var(--toolkit-border-strong)] bg-[var(--toolkit-bg-subtle)] px-4 py-3"
            >
              <p className="text-sm font-medium text-[var(--toolkit-text-strong)]">{p.label}</p>
              <div className="mt-2 space-y-1">
                {p.examples.map(ex => (
                  <p
                    key={ex}
                    className="truncate font-mono text-[11px] text-[var(--toolkit-text-dim)]"
                  >
                    {ex}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Chat Messages */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Chat feedback</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Error messages
        </h2>
        <div className="mt-5 space-y-5">
          <FormRow
            label="No URL provided"
            note="Sent when the command is used with no link."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              maxLength={200}
              onChange={e => setSettings(s => ({ ...s, chatNoUrlMessage: e.target.value }))}
              type="text"
              value={settings.chatNoUrlMessage}
            />
          </FormRow>
          <FormRow
            label="Unsupported link"
            note="Sent when the URL doesn't match any supported platform."
          >
            <input
              className="toolkit-input"
              disabled={isLoading}
              maxLength={200}
              onChange={e => setSettings(s => ({ ...s, chatUnsupportedMessage: e.target.value }))}
              type="text"
              value={settings.chatUnsupportedMessage}
            />
          </FormRow>
        </div>
      </section>

      {/* Command Permissions */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Command permissions</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Minimum role per command
        </h2>
        <p className="mt-1 text-sm leading-6 text-[var(--toolkit-text-muted)]">
          Higher roles always inherit access. Set to{" "}
          <span className="font-medium text-[var(--toolkit-text)]">mod</span> or{" "}
          <span className="font-medium text-[var(--toolkit-text)]">streamer</span> to restrict who
          can trigger clip playback.
        </p>
        <div className="mt-5 -mx-4 overflow-x-auto px-4 sm:-mx-6 sm:px-6 md:mx-0 md:px-0">
          <table className="min-w-[32rem] w-full text-sm">
            <thead>
              <tr className="border-b border-[var(--toolkit-border)]">
                <th className="w-56 py-2 pr-4 text-left text-xs font-medium text-[var(--toolkit-text-muted)]">
                  Command
                </th>
                {PERMISSION_LEVELS.map(level => (
                  <th
                    className="px-3 py-2 text-center text-xs font-medium capitalize text-[var(--toolkit-text-muted)]"
                    key={level}
                  >
                    {level}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {COMMANDS.map(({ key, label, note }) => {
                const current = settings.permissions[key];
                return (
                  <tr
                    className="border-b border-[var(--toolkit-border)] last:border-0"
                    key={key}
                  >
                    <td className="py-3 pr-4">
                      <p className="font-mono text-xs text-[var(--toolkit-text-muted)]">{label}</p>
                      <p className="text-[11px] text-[var(--toolkit-text-dim)]">{note}</p>
                    </td>
                    {PERMISSION_LEVELS.map(level => (
                      <td className="px-3 py-3 text-center" key={level}>
                        <button
                          aria-label={`Set ${key} to ${level}`}
                          className={[
                            "mx-auto flex h-4 w-4 items-center justify-center rounded-full border transition-colors",
                            current === level
                              ? "border-[var(--toolkit-accent)] bg-[var(--toolkit-accent)]"
                              : "border-[var(--toolkit-border-strong)] hover:border-[var(--toolkit-accent)]",
                          ].join(" ")}
                          disabled={isLoading}
                          onClick={() => setPermission(key, level)}
                          type="button"
                        >
                          {current === level && (
                            <span className="block h-2 w-2 rounded-full bg-white" />
                          )}
                        </button>
                      </td>
                    ))}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      {/* Save */}
      <div className="flex items-center gap-4">
        <button
          className="toolkit-button toolkit-button-primary disabled:cursor-not-allowed disabled:opacity-40"
          disabled={isSaving || !isDirty}
          onClick={save}
          type="button"
        >
          {isSaving ? "Saving…" : "Save settings"}
        </button>
        {saveMessage && (
          <span
            className={`text-sm ${
              saveMessage.tone === "success"
                ? "text-[var(--toolkit-success)]"
                : "text-[var(--toolkit-danger)]"
            }`}
          >
            {saveMessage.text}
          </span>
        )}
        {isDirty && !saveMessage && (
          <span className="text-xs text-[var(--toolkit-text-muted)]">Unsaved changes</span>
        )}
      </div>

      {/* Script Generator */}
      <ScriptPanel settings={settings} />
    </div>
  );
}
