"use client";

import { Check, Copy, FileCode2, Plus, Trash2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { toolkitApi, ToolkitApiError } from "@/lib/toolkitApi";

interface VsoCustomUser {
  note: string | null;
  pinnedDurationSec: number;
  pinnedEmbedUrl: string | null;
  username: string;
}

interface VsoSettings {
  chatNoClipsMessage: string;
  clipsWithinDays: number;
  commandName: string;
  customUsers: VsoCustomUser[];
  loadingDelayBufferMs: number;
  obsBrowserSource: string;
  obsScene: string;
  overlayUrl: string;
}

const DEFAULT_SETTINGS: VsoSettings = {
  chatNoClipsMessage: "This streamer doesn't have any clips! :(",
  clipsWithinDays: 120,
  commandName: "!vso",
  customUsers: [],
  loadingDelayBufferMs: 1000,
  obsBrowserSource: "VRF-VSO",
  obsScene: "Screenshare",
  overlayUrl: "https://deutschmark.online/shoutout/",
};

/* ─── Script Generator ─── */

function generateScript(s: VsoSettings): string {
  const hasCustom = s.customUsers.some(u => u.pinnedEmbedUrl);

  const pinnedUrls = s.customUsers
    .filter(u => u.pinnedEmbedUrl)
    .map(u => `        { ${JSON.stringify(u.username)}, ${JSON.stringify(u.pinnedEmbedUrl)} },`)
    .join("\n");

  const pinnedDurations = s.customUsers
    .filter(u => u.pinnedEmbedUrl)
    .map(u => `        { ${JSON.stringify(u.username)}, ${u.pinnedDurationSec}.0 },`)
    .join("\n");

  const pinnedUrlsBlock = hasCustom ? `\n${pinnedUrls}\n    ` : "\n        // No pinned clips configured\n    ";
  const pinnedDurBlock = hasCustom ? `\n${pinnedDurations}\n    ` : "\n    ";

  return `// ================================================================
// Video Shout Out — generated by toolkit.deutschmark.online
// Edit config: https://toolkit.deutschmark.online/tools/video-shout-out
// ================================================================
using System;
using System.Collections.Generic;

public class CPHInline
{
    // ── OBS Configuration ──────────────────────────────────────────
    private const string OBS_SCENE   = ${JSON.stringify(s.obsScene)};
    private const string OBS_SOURCE  = ${JSON.stringify(s.obsBrowserSource)};

    // ── Clip Configuration ─────────────────────────────────────────
    private const int CLIPS_DAYS     = ${s.clipsWithinDays};
    private const int DELAY_BUFFER   = ${s.loadingDelayBufferMs};  // ms added after clip ends

    // ── Overlay URL ────────────────────────────────────────────────
    private const string OVERLAY_URL = ${JSON.stringify(s.overlayUrl)};

    // ── Chat Messages ──────────────────────────────────────────────
    private const string NO_CLIPS_MSG = ${JSON.stringify(s.chatNoClipsMessage)};

    // ── Per-user pinned clips ──────────────────────────────────────
    private static readonly Dictionary<string, string> PinnedClips =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {${pinnedUrlsBlock}};

    private static readonly Dictionary<string, double> PinnedDurations =
        new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase)
    {${pinnedDurBlock}};

    // ──────────────────────────────────────────────────────────────

    public bool Execute()
    {
        string userName        = args["targetUser"].ToString();
        string profileImageUrl = args["targetUserProfileImageUrl"].ToString();

        // Check for a pinned clip override
        string pinnedUrl;
        if (PinnedClips.TryGetValue(userName, out pinnedUrl))
        {
            double dur;
            if (!PinnedDurations.TryGetValue(userName, out dur)) dur = 60.0;
            PlayShoutOut(userName, profileImageUrl, pinnedUrl, "", dur);
            return true;
        }

        // Random clip via Twitch API
        DateTime now   = DateTime.Now;
        var clips      = CPH.GetClipsForUser(userName, now.AddDays(-CLIPS_DAYS), now);
        if (clips.Count == 0) clips = CPH.GetClipsForUser(userName);

        if (clips.Count == 0)
        {
            CPH.SendMessage(NO_CLIPS_MSG);
            return false;
        }

        var clip     = clips[new Random().Next(0, clips.Count)];
        string embed = clip.Url.Replace("twitch.tv/", "twitch.tv/embed?clip=");
        PlayShoutOut(clip.BroadcasterName, profileImageUrl, embed, clip.ThumbnailUrl, clip.Duration);
        return true;
    }

    private void PlayShoutOut(string user, string image, string video,
                              string thumbnail, double durationSec)
    {
        int clipMs = (int)(durationSec * 1000);
        string url = OVERLAY_URL
            + "?user="          + Uri.EscapeDataString(user)
            + "&image="         + Uri.EscapeDataString(image)
            + "&video="         + Uri.EscapeDataString(video)
            + "&thumbnail_url=" + Uri.EscapeDataString(thumbnail)
            + "&time="          + (700 + clipMs);

        CPH.ObsSetBrowserSource(OBS_SCENE, OBS_SOURCE, url);
        CPH.Wait(700 + clipMs + DELAY_BUFFER);
        CPH.ObsSetBrowserSource(OBS_SCENE, OBS_SOURCE, "about:blank");
    }
}`;
}

/* ─── Shared UI helpers ─── */

function FormRow({ label, note, children }: {
  children: React.ReactNode;
  label: string;
  note?: string;
}) {
  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between sm:gap-6">
      <div className="min-w-0 sm:max-w-[220px]">
        <span className="text-sm text-[var(--toolkit-text)]">{label}</span>
        {note && <p className="mt-0.5 text-xs leading-5 text-[var(--toolkit-text-dim)]">{note}</p>}
      </div>
      <div className="w-full sm:max-w-xs">{children}</div>
    </div>
  );
}

function NumberInput({ value, onChange, min, max, step = 1, disabled }: {
  disabled?: boolean;
  max: number;
  min: number;
  onChange: (v: number) => void;
  step?: number;
  value: number;
}) {
  return (
    <input
      className="toolkit-input"
      disabled={disabled}
      max={max}
      min={min}
      onChange={e => {
        const v = parseFloat(e.target.value);
        if (!Number.isNaN(v)) onChange(v);
      }}
      step={step}
      type="number"
      value={value}
    />
  );
}

function TextInput({ value, onChange, placeholder, disabled, maxLength }: {
  disabled?: boolean;
  maxLength?: number;
  onChange: (v: string) => void;
  placeholder?: string;
  value: string;
}) {
  return (
    <input
      className="toolkit-input"
      disabled={disabled}
      maxLength={maxLength}
      onChange={e => onChange(e.target.value)}
      placeholder={placeholder}
      type="text"
      value={value}
    />
  );
}

/* ─── Custom User Row ─── */

function CustomUserRow({
  user,
  onRemove,
  onChange,
}: {
  onChange: (u: VsoCustomUser) => void;
  onRemove: () => void;
  user: VsoCustomUser;
}) {
  return (
    <div className="rounded-[var(--toolkit-radius-md)] border border-[var(--toolkit-border-strong)] bg-[var(--toolkit-bg-subtle)] p-4">
      <div className="flex items-start justify-between gap-3">
        <span className="text-sm font-medium text-[var(--toolkit-text-strong)]">
          @{user.username}
        </span>
        <button
          className="toolkit-button toolkit-button-ghost shrink-0 px-2 py-1 text-xs text-[var(--toolkit-danger)]"
          onClick={onRemove}
          type="button"
        >
          <Trash2 className="h-3.5 w-3.5" />
        </button>
      </div>
      <div className="mt-3 space-y-3">
        <div>
          <label className="mb-1 block text-xs text-[var(--toolkit-text-dim)]">
            Pinned clip embed URL
            <span className="ml-1 text-[var(--toolkit-text-dim)]">(optional — overrides random)</span>
          </label>
          <input
            className="toolkit-input text-xs"
            maxLength={500}
            onChange={e => onChange({ ...user, pinnedEmbedUrl: e.target.value || null })}
            placeholder="https://clips.twitch.tv/embed?clip=SlugHere"
            type="text"
            value={user.pinnedEmbedUrl ?? ""}
          />
        </div>
        <div className="flex gap-4">
          <div className="flex-1">
            <label className="mb-1 block text-xs text-[var(--toolkit-text-dim)]">
              Pinned clip duration (sec)
            </label>
            <input
              className="toolkit-input text-xs"
              max={300}
              min={5}
              onChange={e => {
                const v = parseInt(e.target.value, 10);
                if (!Number.isNaN(v)) onChange({ ...user, pinnedDurationSec: v });
              }}
              type="number"
              value={user.pinnedDurationSec}
            />
          </div>
          <div className="flex-1">
            <label className="mb-1 block text-xs text-[var(--toolkit-text-dim)]">
              Operator note
            </label>
            <input
              className="toolkit-input text-xs"
              maxLength={200}
              onChange={e => onChange({ ...user, note: e.target.value || null })}
              placeholder="e.g. always show charity clip"
              type="text"
              value={user.note ?? ""}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

/* ─── Add User Form ─── */

function AddUserForm({ onAdd, existingUsernames }: {
  existingUsernames: Set<string>;
  onAdd: (u: VsoCustomUser) => void;
}) {
  const [username, setUsername] = useState("");
  const [error, setError] = useState<string | null>(null);

  function submit() {
    const clean = username.replace(/^@/, "").trim().toLowerCase();
    if (!clean) { setError("Enter a username"); return; }
    if (existingUsernames.has(clean)) { setError("Already in list"); return; }
    onAdd({ note: null, pinnedDurationSec: 60, pinnedEmbedUrl: null, username: clean });
    setUsername("");
    setError(null);
  }

  return (
    <div className="flex items-start gap-3">
      <div className="flex-1">
        <input
          className="toolkit-input"
          maxLength={64}
          onChange={e => { setUsername(e.target.value); setError(null); }}
          onKeyDown={e => e.key === "Enter" && submit()}
          placeholder="username (without @)"
          type="text"
          value={username}
        />
        {error && <p className="mt-1 text-xs text-[var(--toolkit-danger)]">{error}</p>}
      </div>
      <button
        className="toolkit-button toolkit-button-secondary shrink-0"
        onClick={submit}
        type="button"
      >
        <Plus className="h-4 w-4" />
        Add
      </button>
    </div>
  );
}

/* ─── Script Panel ─── */

function ScriptPanel({ settings }: { settings: VsoSettings }) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const script = generateScript(settings);

  function copy() {
    navigator.clipboard.writeText(script).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="toolkit-eyebrow">Streamer.bot script</p>
          <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
            Generated C# script
          </h2>
          <p className="mt-1 text-sm leading-6 text-[var(--toolkit-text-muted)]">
            Paste this into Streamer.bot as an Execute C# Code action triggered by the{" "}
            <code className="rounded bg-[var(--toolkit-bg-hover)] px-1.5 py-0.5 text-xs font-mono text-[var(--toolkit-text)]">
              {settings.commandName}
            </code>{" "}
            command. Re-copy after saving any config changes.
          </p>
        </div>
        <div className="flex shrink-0 gap-2">
          <button
            className="toolkit-button toolkit-button-ghost text-xs"
            onClick={() => setExpanded(v => !v)}
            type="button"
          >
            <FileCode2 className="h-4 w-4" />
            {expanded ? "Collapse" : "Preview"}
          </button>
          <button
            className="toolkit-button toolkit-button-primary shrink-0"
            onClick={copy}
            type="button"
          >
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? "Copied!" : "Copy script"}
          </button>
        </div>
      </div>

      {expanded && (
        <pre className="mt-4 overflow-x-auto rounded-[var(--toolkit-radius-md)] border border-[var(--toolkit-border-strong)] bg-[var(--toolkit-bg-subtle)] p-4 text-xs leading-5 text-[var(--toolkit-text-muted)]">
          {script}
        </pre>
      )}

      <div className="mt-4 rounded-[var(--toolkit-radius-md)] border border-[var(--toolkit-border)] bg-[var(--toolkit-bg-subtle)] px-4 py-3">
        <p className="text-xs leading-5 text-[var(--toolkit-text-dim)]">
          <strong className="text-[var(--toolkit-text-muted)]">Streamer.bot setup:</strong> Create a
          command trigger for{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1 font-mono">
            {settings.commandName}
          </code>{" "}
          → Add Target Info action → Execute C# Code (paste script above). The overlay file must be
          accessible at the URL configured in Overlay URL below. OBS WebSocket must be connected in
          Streamer.bot.
        </p>
      </div>
    </section>
  );
}

/* ─── Main Page ─── */

export default function VideoShoutOutPage() {
  const [settings, setSettings] = useState<VsoSettings>(DEFAULT_SETTINGS);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [saveMessage, setSaveMessage] = useState<{ text: string; tone: "success" | "error" } | null>(null);
  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    toolkitApi
      .get<{ settings: VsoSettings }>("/vso-settings")
      .then(data => setSettings(data.settings))
      .catch(err => {
        const msg =
          err instanceof ToolkitApiError && err.status === 401
            ? "Sign in to load your VSO settings."
            : "Couldn't load saved settings. Retry before making changes.";
        setLoadError(msg);
      })
      .finally(() => setIsLoading(false));
  }, []);

  const save = useCallback(async () => {
    if (isSaving) return;
    setIsSaving(true);
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current);

    try {
      const data = await toolkitApi.put<{ settings: VsoSettings }>("/vso-settings", settings);
      setSettings(data.settings);
      setSaveMessage({ text: "Settings saved.", tone: "success" });
    } catch (err) {
      const msg =
        err instanceof ToolkitApiError
          ? err.message || "Save failed."
          : "Save failed.";
      setSaveMessage({ text: msg, tone: "error" });
    } finally {
      setIsSaving(false);
      saveTimerRef.current = setTimeout(() => setSaveMessage(null), 4000);
    }
  }, [isSaving, settings]);

  function updateCustomUser(index: number, updated: VsoCustomUser) {
    setSettings(s => {
      const users = [...s.customUsers];
      users[index] = updated;
      return { ...s, customUsers: users };
    });
  }

  function removeCustomUser(index: number) {
    setSettings(s => ({
      ...s,
      customUsers: s.customUsers.filter((_, i) => i !== index),
    }));
  }

  function addCustomUser(u: VsoCustomUser) {
    setSettings(s => ({ ...s, customUsers: [...s.customUsers, u] }));
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <section className="toolkit-surface px-4 py-5 text-[var(--toolkit-text-strong)] sm:px-6 sm:py-7">
        <p className="toolkit-eyebrow">Shout-out workflow</p>
        <h1 className="mt-4 text-2xl font-semibold tracking-[-0.06em] sm:text-3xl">
          Video Shout Out
        </h1>
        <p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--toolkit-text-muted)]">
          Configure the{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1.5 py-0.5 text-xs font-mono">
            {settings.commandName}
          </code>{" "}
          command that pulls a random Twitch clip for the target streamer and plays it as an OBS
          browser source overlay. Save your config, then copy the generated Streamer.bot script
          below.
        </p>
      </section>

      {loadError && (
        <div className="toolkit-surface border-[var(--toolkit-danger)]/30 px-4 py-4 sm:px-6">
          <p className="text-sm text-[var(--toolkit-danger)]">{loadError}</p>
        </div>
      )}

      {/* OBS + Command */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">OBS & command</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Scene and source configuration
        </h2>
        <div className="mt-5 space-y-5">
          <FormRow
            label="Command trigger"
            note="Chat command that fires the shout out (must start with !)."
          >
            <TextInput
              disabled={isLoading}
              maxLength={32}
              onChange={v => setSettings(s => ({ ...s, commandName: v }))}
              placeholder="!vso"
              value={settings.commandName}
            />
          </FormRow>
          <div className="border-t border-[var(--toolkit-border)] pt-5" />
          <FormRow
            label="OBS scene name"
            note="The scene Streamer.bot will activate before showing the overlay."
          >
            <TextInput
              disabled={isLoading}
              maxLength={100}
              onChange={v => setSettings(s => ({ ...s, obsScene: v }))}
              placeholder="Screenshare"
              value={settings.obsScene}
            />
          </FormRow>
          <FormRow
            label="Browser source name"
            note="Name of the browser source in OBS that displays the shout-out overlay."
          >
            <TextInput
              disabled={isLoading}
              maxLength={100}
              onChange={v => setSettings(s => ({ ...s, obsBrowserSource: v }))}
              placeholder="VRF-VSO"
              value={settings.obsBrowserSource}
            />
          </FormRow>
        </div>
      </section>

      {/* Clip Settings */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Clip settings</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Clip search and timing
        </h2>
        <div className="mt-5 space-y-5">
          <FormRow
            label="Clip lookback (days)"
            note="Only clips created within this many days are eligible. Falls back to all-time if none are found."
          >
            <NumberInput
              disabled={isLoading}
              max={365}
              min={1}
              onChange={v => setSettings(s => ({ ...s, clipsWithinDays: v }))}
              value={settings.clipsWithinDays}
            />
          </FormRow>
          <div className="border-t border-[var(--toolkit-border)] pt-5" />
          <FormRow
            label="Post-clip delay buffer (ms)"
            note="Extra milliseconds added after the clip finishes before the overlay is cleared."
          >
            <NumberInput
              disabled={isLoading}
              max={10000}
              min={0}
              step={100}
              onChange={v => setSettings(s => ({ ...s, loadingDelayBufferMs: v }))}
              value={settings.loadingDelayBufferMs}
            />
          </FormRow>
        </div>
      </section>

      {/* Overlay URL */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Overlay</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Overlay URL
        </h2>
        <p className="mt-1 text-sm leading-6 text-[var(--toolkit-text-muted)]">
          The HTML page OBS loads as the browser source. Use the hosted path or a local{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1 font-mono text-xs">
            file:///
          </code>{" "}
          path to your{" "}
          <code className="rounded bg-[var(--toolkit-bg-hover)] px-1 font-mono text-xs">
            shoutout.html
          </code>.
        </p>
        <div className="mt-5">
          <input
            className="toolkit-input"
            disabled={isLoading}
            maxLength={500}
            onChange={e => setSettings(s => ({ ...s, overlayUrl: e.target.value }))}
            placeholder="https://deutschmark.online/shoutout/ or file:///d:/path/shoutout.html"
            type="text"
            value={settings.overlayUrl}
          />
        </div>
      </section>

      {/* Chat */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Chat feedback</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          No-clips message
        </h2>
        <div className="mt-5">
          <FormRow
            label="Message"
            note="Sent to chat when the target streamer has no clips available."
          >
            <TextInput
              disabled={isLoading}
              maxLength={200}
              onChange={v => setSettings(s => ({ ...s, chatNoClipsMessage: v }))}
              placeholder="This streamer doesn't have any clips! :("
              value={settings.chatNoClipsMessage}
            />
          </FormRow>
        </div>
      </section>

      {/* Per-user overrides */}
      <section className="toolkit-surface px-4 py-5 sm:px-6 sm:py-6">
        <p className="toolkit-eyebrow">Per-user overrides</p>
        <h2 className="mt-3 text-base font-semibold text-[var(--toolkit-text-strong)]">
          Pinned clips
        </h2>
        <p className="mt-1 text-sm leading-6 text-[var(--toolkit-text-muted)]">
          Always play a specific clip for a streamer instead of picking randomly. Useful for
          highlight-reel moments or streamers with few clips.
        </p>

        <div className="mt-5 space-y-3">
          {settings.customUsers.length === 0 && (
            <p className="text-sm text-[var(--toolkit-text-dim)]">
              No per-user overrides configured.
            </p>
          )}
          {settings.customUsers.map((u, i) => (
            <CustomUserRow
              key={u.username}
              onChange={updated => updateCustomUser(i, updated)}
              onRemove={() => removeCustomUser(i)}
              user={u}
            />
          ))}
        </div>

        {settings.customUsers.length < 50 && (
          <div className="mt-4 border-t border-[var(--toolkit-border)] pt-4">
            <AddUserForm
              existingUsernames={new Set(settings.customUsers.map(u => u.username))}
              onAdd={addCustomUser}
            />
          </div>
        )}
      </section>

      {/* Save */}
      <div className="flex items-center justify-between gap-4">
        {saveMessage ? (
          <p
            className={`text-sm ${saveMessage.tone === "success" ? "text-[var(--toolkit-success)]" : "text-[var(--toolkit-danger)]"}`}
          >
            {saveMessage.text}
          </p>
        ) : (
          <span />
        )}
        <button
          className="toolkit-button toolkit-button-primary"
          disabled={isLoading || isSaving}
          onClick={save}
          type="button"
        >
          {isSaving ? "Saving…" : "Save settings"}
        </button>
      </div>

      {/* Script Generator */}
      <ScriptPanel settings={settings} />
    </div>
  );
}
